package ru.tsystems.divider.utils.constants

const val NATURE_VERSION = "version"
const val NATURE_EPIC_STATUS = "epicStatus"
const val NATURE_EPIC_COLOR = "epicColor"
const val NATURE_STATUS = "status"
const val NATURE_PRIORITY = "priority"
const val NATURE_RESOLUTION = "resolution"
const val NATURE_SPRINT = "sprint"
const val NATURE_KEYWORD = "keyword"
const val NATURE_ISSUE_TYPE = "issueType"
const val NATURE_COMPONENT = "component"
const val NATURE_LABEL = "label"
const val NATURE_TEAM = "team"
const val NATURE_DEFAULT = "feature"
